version: "3.8"
services:
  api:
    build: .
    env_file:
      - .env
    command: uv run main.py
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - redis

  worker:
    build: .
    env_file:
      - .env
    command: uv run taskiq worker src.infrastructure.taskiq_app:broker
    depends_on:
      - redis


  redis:
    image: redis:7-alpine
