version: "3.8"
services:
  api:
    build: .
    env_file:
      - .env
    command: uv run main.py
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    env_file:
      - .env
    command: uv run celery -A src.infrastructure.celery_app worker --loglevel=INFO -c 5
    depends_on:
      - redis
    restart: always


  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--port", "6379"]
